const {routesToSnippets, redirectSourcePaths, REDIRECT_STATUS} = require('../../../bin/lib/routes-to-vcl');

describe('redirectSourcePaths', () => {
    test('emits a single slash-free key for an optional trailing slash', () => {
        expect(redirectSourcePaths({pattern: '^/donate/?$', redirect: '/x'}))
            .toEqual(['/donate']);
    });

    test('ignores an optional trailing query group', () => {
        expect(redirectSourcePaths({pattern: '^/jobs/?(\\?.*)?$', redirect: '/x'}))
            .toEqual(['/jobs']);
    });

    test('treats a missing end anchor as an exact path', () => {
        expect(redirectSourcePaths({pattern: '^/info/donate/?', redirect: '/x'}))
            .toEqual(['/info/donate']);
    });

    test('expands simple alternation into one key per alternative', () => {
        expect(redirectSourcePaths({pattern: '^/madewithcode-(name|card)/?$', redirect: '/x'}))
            .toEqual(['/madewithcode-name', '/madewithcode-card']);
    });

    test('expands an optional alternation group (matches the empty case too)', () => {
        expect(redirectSourcePaths({pattern: '^/makey(piano|drum)?/?$', redirect: '/x'}))
            .toEqual(['/makeypiano', '/makeydrum', '/makey']);
    });

    test('throws on a capturing/dynamic pattern rather than dropping it into the table', () => {
        expect(() => redirectSourcePaths({pattern: '^/projects/(\\d+)$', redirect: '/x'}))
            .toThrow(/not a literal path/);
    });
});

describe('routesToSnippets', () => {
    const routes = [
        {name: 'about', pattern: '^/about/?$'},
        {name: 'donate-redirect', pattern: '^/donate/?$', redirect: 'https://example.org/donate'}
    ];
    const snippets = routesToSnippets(routes);
    const byName = name => snippets.find(s => s.name === name).content;

    test('returns the three generated snippets with the expected names and types', () => {
        expect(snippets.map(s => `${s.name}:${s.type}`)).toEqual([
            'app-routes-tables:init',
            'app-routes-recv:recv',
            'app-routes-error:error'
        ]);
    });

    test('every snippet carries the generated provenance header', () => {
        snippets.forEach(s => expect(s.content).toMatch(/^# Generated by bin\/configure-fastly\.js/));
    });

    test('the table maps each redirect source to a single slash-free key', () => {
        const table = byName('app-routes-tables');
        expect(table).toContain('table redirects {');
        expect(table).toContain('"/donate": "https://example.org/donate",');
        expect(table).not.toContain('"/donate/":');
    });

    test('recv keys the lookup off a slash-normalized path without redirecting for the slash', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('set var.path = regsub(req.url.path, "(.)/+$", "\\1");');
        expect(recv).toContain('set var.redirect = table.lookup(redirects, var.path, "");');
        expect(recv).toContain(`error ${REDIRECT_STATUS};`);
        // The request URL is never rewritten to strip a trailing slash.
        expect(recv).not.toContain('if (var.path != req.url.path)');
    });

    test('recv keeps the explicit tip_bar and embed redirects', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('regsub(req.url, "tip_bar=", "tutorial=")');
        expect(recv).toContain('"/projects/" + re.group.1 + "/embed"');
    });

    test('recv rewrites app routes to their static html shell', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('if (req.url.path ~ "^/about/?$") {');
        expect(recv).toContain('set req.url = "/about.html";');
    });

    test('recv leaves the backend split and host handling to recv-condition', () => {
        // Backend selection cannot live in a snippet (the #FASTLY recv default-backend
        // assignment runs after snippets and would clobber it), so none of it is emitted.
        const recv = byName('app-routes-recv');
        expect(recv).not.toContain('set req.backend');
        expect(recv).not.toContain('set req.http.host');
        expect(recv).not.toContain('return(pass)');
    });

    test('a redirect route is not rendered into the app-route rewrite chain', () => {
        const recv = byName('app-routes-recv');
        expect(recv).not.toContain('set req.url = "/donate-redirect.html";');
    });

    test('the error snippet turns the reused status into a 301', () => {
        const error = byName('app-routes-error');
        expect(error).toContain(`if (obj.status == ${REDIRECT_STATUS}) {`);
        expect(error).toContain('set obj.status = 301;');
        expect(error).toContain('set obj.http.Location = req.http.X-Redirect-Location;');
    });
});
