const {routesToSnippets, redirectSourcePaths, REDIRECT_STATUS} = require('../../../bin/lib/routes-to-vcl');

const options = {
    staticCondition: 'req.url~"^(/js/|/css/)"',
    bucketName: 'scratch-www-test.s3.amazonaws.com',
    languageKeys: ['en', 'es', 'fr']
};

describe('redirectSourcePaths', () => {
    test('emits both slashed and unslashed keys for an optional trailing slash', () => {
        expect(redirectSourcePaths({pattern: '^/donate/?$', redirect: '/x'}))
            .toEqual(['/donate', '/donate/']);
    });

    test('ignores an optional trailing query group', () => {
        expect(redirectSourcePaths({pattern: '^/jobs/?(\\?.*)?$', redirect: '/x'}))
            .toEqual(['/jobs', '/jobs/']);
    });

    test('treats a missing end anchor as an exact path', () => {
        expect(redirectSourcePaths({pattern: '^/info/donate/?', redirect: '/x'}))
            .toEqual(['/info/donate', '/info/donate/']);
    });

    test('expands simple alternation into one key per alternative', () => {
        expect(redirectSourcePaths({pattern: '^/madewithcode-(name|card)/?$', redirect: '/x'}))
            .toEqual(['/madewithcode-name', '/madewithcode-name/', '/madewithcode-card', '/madewithcode-card/']);
    });

    test('expands an optional alternation group (matches the empty case too)', () => {
        expect(redirectSourcePaths({pattern: '^/makey(piano|drum)?/?$', redirect: '/x'}))
            .toEqual([
                '/makeypiano', '/makeypiano/',
                '/makeydrum', '/makeydrum/',
                '/makey', '/makey/'
            ]);
    });

    test('throws on a capturing/dynamic pattern rather than dropping it into the table', () => {
        expect(() => redirectSourcePaths({pattern: '^/projects/(\\d+)$', redirect: '/x'}))
            .toThrow(/not a literal path/);
    });
});

describe('routesToSnippets', () => {
    const routes = [
        {name: 'about', pattern: '^/about/?$'},
        {name: 'donate-redirect', pattern: '^/donate/?$', redirect: 'https://example.org/donate'}
    ];
    const snippets = routesToSnippets(routes, options);
    const byName = name => snippets.find(s => s.name === name).content;

    test('returns the four generated snippets with the expected names and types', () => {
        expect(snippets.map(s => `${s.name}:${s.type}`)).toEqual([
            'app-routes-tables:init',
            'app-routes-recv:recv',
            'app-routes-error:error',
            'app-routes-fetch:fetch'
        ]);
    });

    test('every snippet carries the generated provenance header', () => {
        snippets.forEach(s => expect(s.content).toMatch(/^# Generated by bin\/configure-fastly\.js/));
    });

    test('the table maps each redirect source path to its destination', () => {
        const table = byName('app-routes-tables');
        expect(table).toContain('table redirects {');
        expect(table).toContain('"/donate": "https://example.org/donate",');
        expect(table).toContain('"/donate/": "https://example.org/donate",');
    });

    test('recv looks up the redirect table and raises the reused status', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('set var.redirect = table.lookup(redirects, req.url.path, "");');
        expect(recv).toContain(`error ${REDIRECT_STATUS};`);
    });

    test('recv keeps the explicit tip_bar and embed redirects', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('regsub(req.url, "tip_bar=", "tutorial=")');
        expect(recv).toContain('"/projects/" + re.group.1 + "/embed"');
    });

    test('recv rewrites app routes to their static html shell and preserves the backend split', () => {
        const recv = byName('app-routes-recv');
        expect(recv).toContain('if (req.url.path ~ "^/about/?$") {');
        expect(recv).toContain('set req.url = "/about.html";');
        expect(recv).toContain('set req.backend = F_s3;');
        expect(recv).toContain('set req.http.host = "scratch-www-test.s3.amazonaws.com";');
        expect(recv).toContain('accept.language_lookup("en:es:fr", "en", std.tolower(req.http.Accept-Language))');
    });

    test('a redirect route is not rendered into the app-route rewrite chain', () => {
        const recv = byName('app-routes-recv');
        expect(recv).not.toContain('set req.url = "/donate-redirect.html";');
    });

    test('the error snippet turns the reused status into a 301', () => {
        const error = byName('app-routes-error');
        expect(error).toContain(`if (obj.status == ${REDIRECT_STATUS}) {`);
        expect(error).toContain('set obj.status = 301;');
        expect(error).toContain('set obj.http.Location = req.http.X-Redirect-Location;');
    });

    test('the fetch snippet applies the S3 TTL rules to the pass condition', () => {
        const fetch = byName('app-routes-fetch');
        expect(fetch).toContain('if (!(req.url~"^(/js/|/css/)")) {');
        expect(fetch).toContain('set beresp.ttl = 0s;');
    });
});
